### PR TITLE
Connection pooling

### PR DESCRIPTION
**Pull request by bhenderson**
this is my first (public) attempt to solve connection pooling for #49

am I on the right track?

obviously I would add setting size and disabling.

### CODE REVIEW

**Comment by ryansch** [comment]
Honestly I spent some time trying to get that to work and ended up realizing that net-http-persistent can't get away from raising `Timeout::Error` because it relies on net-http.

I wrote https://github.com/outstand/faraday_persistent_excon instead and it's been working great in production for quite some time.  I'd like to eventually remove the faraday specific pieces and get it merged to excon itself.

**Comment by drbrain** [comment]
What is the problem with raising `Timeout::Error` in net/http?

In modern Ruby the only place `Timeout.timeout` is used [is during connect](https://github.com/ruby/ruby/blob/trunk/lib/net/http.rb#L884-L891).

**Comment by drbrain** [comment]
Note that master has connection pooling enabled using the connection-pool gem, please try it out.

**Comment by bhaibel** [comment]
Thank you!

--Betsy

**Comment by ryansch** [comment]
I've had nothing but headaches with `Timeout.timeout` in our threaded code.  There's honestly no reason that net-http couldn't use socket timeouts instead of spawning a thread that might raise at some odd location.

That aside, I think it's pretty great that you were able to add connection-pool support!

**Comment by bhenderson** [comment]
closing. thanks.

**Pull request closed without merging**
